### ISSUE TITLE
First issue

### ISSUE THREAD

**Issue by saberistic** [Amirsharifico/Private-ugly-todo#1]
- [x] add a readme file
- [x] rename html file to index and move to src folder
- [x] make it a npm package with `npm init` command
- [x] make a `.gitignore` file and add `node_modiles` to `.gitignore` file
- [x] add static-server as a dependency
- [x] have npm start to serve src folder with static-serve
- [x] make a docker file

**Comment by Amirsharifico** [comment]
I need more information about last 2 issues,
